# Generated by Django 4.2.9 on 2024-02-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='taskDescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
