# Generated by Django 4.2.9 on 2024-02-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0002_alter_tasks_taskdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='taskDescription',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
