# Generated by Django 4.2.9 on 2024-02-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0005_tasks_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
